# -*- coding: utf-8 -*-
"""keccak256.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iv7tNLM9ZuoLFq3ss9AjRAp3wGsUzI5h
"""

import haslib
from eth_hash.auto import keccak

str = keccak(b'tiohalu')
str_hex = str.hexdigest()

pip install eth-hash[pycryptodome]

from Crypto.Hash import keccak
k = keccak.new(digest_bits=256)
k.update(b'Hello World nama gue tio')
print(k.hexdigest())

